### ISSUE TITLE
ssh based encryption pub/priv/signing 

### ISSUE THREAD

**Issue by despiegk** [Incubaid/research#3]
use ssh-agent to allow
- encryption using pub key
- decryption using priv key with loaded sshkey
- signing using priv key
- verification using pub key

probably need
- https://github.com/Jumpscale/lib9/issues/72 : nacl & encryption lib in js9

put this code in encryption lib

**Comment by despiegk** [comment]
hamdy has already done work here, make sure it gets leveraged

**Comment by rkhamis** [comment]
Work is documented here: https://docs.google.com/document/u/1/d/1jIMKwdtMP1hg7mU9beRSWw1kIGS_2EfmwPS-Bvee5uQ/edit?ts=59ef5783

**Comment by rkhamis** [comment]
According to the conclusions @Hamdy reached, this is not optimal. How should we proceed?
